services:
  backend:
    build: ./backend
    environment:
      - PG_URI=postgresql://postgres:postgres@db:5432/kemjar
      - APP_PORT=8888
    ports:
      - "3000:8888"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:15.15-trixie
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kemjar
      - PGUSER=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "kemjar"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s