services:
  backend:
    build: ./backend
    environment:
      - PG_STRING=postgresql://postgres:postgres@db:5432/kemjar
      - APP_PORT=:8080
    ports:
      - "3000:8080"
    depends_on:
      db:
        condition: service_healthy
    watch:
      - action: rebuild
      - path: ./backend
  
  db:
    image: postgres:15.15-trixie
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kemjar
      - PGUSER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "kemjar"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s